Omit medium-observed targets
USGS-R/drb-do-ml pull request #154
Opened 2022-08-24 22:12 UTC by lekoenig

This PR makes the following code changes to simplify the pipeline:

- add an object called `min_obs_days` to `_targets.R`. `min_obs_days` is used to define the minimum number of observation-days a site should have before it's considered "well-observed" and used in the model. `min_obs_days` replaces `"300"` in `p2_well_observed_sites` and therefore serves as an input that can be modified by the user. 
- define `min_obs_days <- 100` so that our "well-observed" site targets now reflect our decision to use what we were previously calling "medium-observed" sites (see #122 for more detail)
- omit targets that refer to "med-observed" sites in `2_process.R` and `2a_model.R`

Closes #148

2022-08-31 14:35 UTC, lekoenig commented
The changes in this PR don't include any edits to the model config files (e.g. `site_set`), but probably should. Should I just update model config files to use "well-obs" for `site_set`?

2022-08-31 18:17 UTC, jsadler2 approved these changes
This looks good to me.

We have the old "well-observed" results to look back on if we want, correct?

2022-09-28 19:49 UTC, lekoenig commented
Jeff and I decided that the simplest approach was to hard-code in the path of the well-obs zarr files (I added a note in `2a_model.R` letting the user know about this dependency) and to remove the variable `site_set` from each of the model config files.

@jsadler2, do you mind taking a quick look at the snakefile/cfg files? I haven't tried running this yet because I want to first resolve the issue I'm having running the pipeline with `tmmn` on tallgrass.

2022-09-30 17:41 UTC, jsadler2 requested changes
This looks good. Thanks, @lekoenig 

I do suggest one additional comment saying where our well observed threshold is defined (_targets.R). 

Also, when I tried to run this, I found that the 2a_model/src/models/visualize_models.smk file has `site_set` still in it. So that needs to be changed.

2022-09-30 20:39 UTC, jsadler2 approved these changes
👍

2022-09-30 21:03 UTC, merged